pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    ls -la
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(cat rust-toolchain) --profile=minimal
    echo "##vso[task.prependpath]$HOME/.cargo/bin"
  displayName: 'Install Rust'

- script: |
    sudo apt-get update
    sudo apt-get install -y libmysql++-dev
  displayName: Install libmysql

- script: |
    rustc -Vv
    cargo -V
  displayName: Query rust and cargo versions

- script : cargo test --features "sqlite"
  displayName: 'Test project with sqlite backend'

- script : cargo test --features "mysql"
  displayName: 'Test project with mysql backend'
